### ISSUE TITLE
Feature requests： can user edit the config file 

### ISSUE THREAD

**Issue by SimplyY** [aminya/package-switch#3]
just like 
![image](https://cloud.githubusercontent.com/assets/8455579/10307036/e56402ee-6c5d-11e5-97f7-a33be46fbaf0.png)

in project-manager https://github.com/danielbrodin/atom-project-manager

**Comment by fstiewitz** [comment]
The global config file is called `package-switch.bundles` in `.atom`. If it doesn't exist then you don't have any global bundles configured, in which case you should execute `package-switch:create` to create one. Local config files (`.package-switch.cson`) can only be edited through my UI. If you want to edit it manually then you'd have to open it in another editor.

EDIT: Is there a reason why you want to edit it manually instead of using `package-switch:create/edit/remove` and the UI ?

**Comment by SimplyY** [comment]
UI is not very efficient in editing. 
And I want to manage a lot of packages.

**Comment by fstiewitz** [comment]
I guess a `package-switch:open-global-config-file` and a button to open local ones as a text file will do.

**Comment by SimplyY** [comment]
good job.

and I have a question.
when we create some package-list.
can we load package-list in init.coffee depend on project main files type(of course setting by user)?

and I have write an article about making your atom quicker start by your package.
http://simplyy.space/blog/article/make%20your%20atom%20quicker%20start

**Comment by SimplyY** [comment]
In the article last step

![image](https://cloud.githubusercontent.com/assets/8455579/10332786/3c2c43d4-6d12-11e5-9099-cd2085d74bbd.png)

and I want to make the last step automatic. 
I wish you can help me

**Comment by fstiewitz** [comment]
If you open atom with only one active project then my package will automatically load the `.package-switch.cson` from said project.
Together with https://github.com/deprint/package-switch#save-and-restore-package-states this could be used to prevent other packages from being loaded when Atom starts. The problem is that this is very buggy because Atom has no API for package management. I'd have to hack my way around Atom's package manager.
I'll see what can and can't be done about this.

**Comment by fstiewitz** [comment]
I was able to fix the package and also add a few new settings. I'll refer to the [CHANGELOG](https://github.com/deprint/package-switch/blob/master/CHANGELOG.md) for details.
